### ISSUE TITLE
Qt.MOC not running in parallel

### ISSUE THREAD

**Issue by Redbeanw44602** [xmake-io/xmake#6933]
### Xmake Version

dev

### Operating System Version and Architecture

Manjaro Linux

### Describe Bug

`qt.moc` rules were not executed in parallel during build, causing them to take a significant amount of time.

### Expected Behavior

Execute moc in parallel.

### Project Configuration

https://github.com/PenUniverse/PenMods/blob/main/xmake.lua

### Additional Information and Error Logs

```
147ef59b5d5aeb19519e98ed07179ff84edaa5c9 is the first bad commit
commit 147ef59b5d5aeb19519e98ed07179ff84edaa5c9
Author: ruki <waruqi@gmail.com>
Date:   Mon Mar 31 22:32:02 2025 +0800

    fix rule batches

 xmake/actions/build/target_utils.lua | 56 ++++++++++++++++++++++++--------------------------------
 1 file changed, 24 insertions(+), 32 deletions(-)
```

**Comment by waruqi** [comment]
mac 下编译不过，给个最小可复现的例子

```
[  3%]: cache compiling.release src/base/Base.h
error: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/usr/include/sys/resource.h:203:2: error: unknown type name 'uint8_t'
  203 |         uint8_t  ri_uuid[16];
      |         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/usr/include/sys/resource.h:204:2: error: unknown type name 'uint64_t'
  204 |         uint64_t ri_user_time;
      |         ^
```

**Comment by Redbeanw44602** [comment]
[issue-6933.zip](https://github.com/user-attachments/files/22969908/issue-6933.zip)

@waruqi Try this, `xmake -v`, xmake will run moc one by one

**Comment by waruqi** [comment]
try this patch. https://github.com/xmake-io/xmake/pull/6937

**Comment by Redbeanw44602** [comment]
> try this patch. [#6937](https://github.com/xmake-io/xmake/pull/6937)

It works, thank you!
