### ISSUE TITLE
yacc output directory no longer added to include directories (since 2.6.6)

### ISSUE THREAD

**Issue by cmeerw** [xmake-io/xmake#2702]
### Xmake Version

2.6.9

### Operating System Version and Architecture

Ubuntu 22.04

### Describe Bug

`yacc`/`bison` generated header files should be made available to other source files - this worked until 2.6.5, but no longer works with 2.6.6

### Expected Behavior

`bison` generates `foo.tab.hpp` - this should should be found when included from `main.cpp`, but isn't any more.

### Project Configuration

xmake.lua:
```
set_languages("cxx14")

target("foo")
   set_kind("static")

   add_files("foo.yy", { rule = "yacc" })
   add_files("main.cpp")
```

main.cpp
```
#include "foo.tab.hpp"

int main() { }
```

foo.yy
```
%language "C++"
%defines
%code
{
extern int yylex (void *scanner);
}

%%

bar:
```

### Additional Information and Error Logs

```
$ xmake
checking for platform ... linux
checking for architecture ... armv7a
[ 20%]: compiling.yacc foo.yy
[ 40%]: ccache compiling.release main.cpp
error: main.cpp:1:10: fatal error: foo.tab.hpp: No such file or directory
    1 | #include "foo.tab.hpp"
      |          ^~~~~~~~~~~~~
compilation terminated.
  > in main.cpp
```

**Comment by cmeerw** [comment]
actually works with `add_rules`, closing...

**Comment by cmeerw** [comment]
Hmm... but shouldn't `add_files` with `rule` be equivalent to `add_rules` and `add_files`?

**Comment by waruqi** [comment]
Not exactly equivalent, the rules of add_rules execute some extra scripts, but add_files/rules do not.

please use add_rules for yacc, if you want ti export includes

**Comment by waruqi** [comment]
It is not a bug, you can use add_rules.
